[workspace]
resolver = "3"
members = ["crates/hux-core", "crates/hux-addon"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
rust-version = "1.85"

[workspace.dependencies]
anyhow = "1"
hashbrown = "0.15"
memmap2 = "0.9"
yaml-rust2 = "0.13.0"

[profile.release]
lto = "thin"
